-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE TOURISM_MARKETING;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.PROPERTIES (
  PROPERTY_ID VARCHAR(20) NOT NULL, PROPERTY_NAME VARCHAR(200), DESTINATION VARCHAR(50), CATEGORY VARCHAR(30), ROOMS_TOTAL INT, STAR_RATING FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RESERVATIONS (
  RESERVATION_ID VARCHAR(30) NOT NULL, PROPERTY_ID VARCHAR(20), GUEST_ID VARCHAR(20), CHECK_IN DATE, CHECK_OUT DATE, ROOM_NIGHTS INT, RATE FLOAT, TOTAL_REVENUE FLOAT, CHANNEL VARCHAR(30), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.GUESTS (
  GUEST_ID VARCHAR(20) NOT NULL, NATIONALITY VARCHAR(50), SEGMENT VARCHAR(30), LIFETIME_STAYS INT, LIFETIME_SPEND FLOAT, LOYALTY_TIER VARCHAR(20), FIRST_STAY DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.REVIEWS (
  REVIEW_ID VARCHAR(30) NOT NULL, PROPERTY_ID VARCHAR(20), GUEST_ID VARCHAR(20), REVIEW_DATE DATE, RATING FLOAT, CATEGORY VARCHAR(30), SENTIMENT_SCORE FLOAT, REVIEW_TEXT VARCHAR(2000), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
