-- Generated from generator/demo_specs/aws-thailand-tourism-marketing.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-tourism-marketing
-- This is the schema that is actually deployed for THAILAND_TOURISM_MARKETING.

-- Alerts fire on the bottom tail of Campaign ROI
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_CAMPAIGN_ROI) AS T
  FROM RAW.SOCIAL_CONTENT
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_CAMPAIGN_ROI <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_CAMPAIGN_ROI), 2) AS AVG_CAMPAIGN_ROI,
  ROUND(AVG(f.KPI_CONVERSION_RATE), 2) AS AVG_CONVERSION_RATE,
  ROUND(AVG(f.KPI_SOCIAL_MEDIA_SHARE), 2) AS AVG_SOCIAL_MEDIA_SHARE,
  ROUND(AVG(f.KPI_SEARCH_INTENT), 2) AS AVG_SEARCH_INTENT,
  ROUND(AVG(f.KPI_INFLUENCER_IMPACT), 2) AS AVG_INFLUENCER_IMPACT
FROM RAW.SOCIAL_CONTENT f
JOIN RAW.THAI_DESTINATION_DATA e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_CAMPAIGN_ROI), 2) AS AVG_CAMPAIGN_ROI,
  ROUND(AVG(f.KPI_CONVERSION_RATE), 2) AS AVG_CONVERSION_RATE,
  ROUND(AVG(f.KPI_SOCIAL_MEDIA_SHARE), 2) AS AVG_SOCIAL_MEDIA_SHARE,
  ROUND(AVG(f.KPI_SEARCH_INTENT), 2) AS AVG_SEARCH_INTENT,
  ROUND(AVG(f.KPI_INFLUENCER_IMPACT), 2) AS AVG_INFLUENCER_IMPACT
FROM RAW.SOCIAL_CONTENT f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_CAMPAIGN_ROI) AS KPI_CAMPAIGN_ROI, AVG(KPI_CONVERSION_RATE) AS KPI_CONVERSION_RATE, AVG(KPI_SOCIAL_MEDIA_SHARE) AS KPI_SOCIAL_MEDIA_SHARE, AVG(KPI_SEARCH_INTENT) AS KPI_SEARCH_INTENT, AVG(KPI_INFLUENCER_IMPACT) AS KPI_INFLUENCER_IMPACT FROM RAW.SOCIAL_CONTENT),
     en AS (SELECT SUM(KPI_DIGITAL_SPEND_MTD) AS KPI_DIGITAL_SPEND_MTD, SUM(KPI_REACH_UNIQUE) AS KPI_REACH_UNIQUE FROM RAW.THAI_DESTINATION_DATA)
  SELECT 1 AS SORT_ORDER, 'Campaign ROI' AS TITLE, KPI_CAMPAIGN_ROI AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CAMPAIGN_ROI), 1) AS DECIMAL(38,1))) || 'x' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Digital Spend (MTD)' AS TITLE, KPI_DIGITAL_SPEND_MTD AS VALUE_NUM, '฿' || TO_VARCHAR(CAST(ROUND(((KPI_DIGITAL_SPEND_MTD) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Reach (Unique)' AS TITLE, KPI_REACH_UNIQUE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_REACH_UNIQUE) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Conversion Rate' AS TITLE, KPI_CONVERSION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CONVERSION_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Social Media Share' AS TITLE, KPI_SOCIAL_MEDIA_SHARE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SOCIAL_MEDIA_SHARE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Search Intent' AS TITLE, KPI_SEARCH_INTENT AS VALUE_NUM, '↑' || ' ' || TO_VARCHAR(CAST(ROUND((KPI_SEARCH_INTENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Influencer Impact' AS TITLE, KPI_INFLUENCER_IMPACT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_INFLUENCER_IMPACT), 1) AS DECIMAL(38,1))) || 'x' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
