-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Destination Marketing Intelligence
-- ============================================================================
USE DATABASE MARKETING_INTEL;
USE SCHEMA ML;

-- ML.FORECAST: CAMPAIGN_PERFORMANCE_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CAMPAIGN_PERFORMANCE_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CAMPAIGN_ROI'),
  SERIES_COLNAME => 'CAMPAIGN_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.CAMPAIGN_PERFORMANCE_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.CAMPAIGN_PERFORMANCE_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: SENTIMENT_SHIFT_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.SENTIMENT_SHIFT_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SOCIAL_SENTIMENT_TRENDS'),
  SERIES_COLNAME => 'MARKET_TOPIC',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.SENTIMENT_SHIFT_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.SENTIMENT_SHIFT_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SOCIAL_SENTIMENT_TRENDS'), SERIES_COLNAME => 'MARKET_TOPIC', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

