-- ============================================================================
-- 99_RESET.SQL — Reset Destination Marketing Intelligence to clean demo state
-- ============================================================================
USE DATABASE MARKETING_INTEL;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_ANALYZE_SOCIAL SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_TRENDS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_REPORTS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CAMPAIGN_ROI REFRESH;
ALTER DYNAMIC TABLE CURATED.SOCIAL_SENTIMENT_TRENDS REFRESH;
ALTER DYNAMIC TABLE CURATED.TRENDING_TOPICS REFRESH;
ALTER DYNAMIC TABLE CURATED.COMPETITIVE_POSITIONING REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM MARKETING_INTEL.RAW.SOCIAL_CONTENT → 500000
-- SELECT COUNT(*) FROM MARKETING_INTEL.RAW.CAMPAIGNS → 350
-- SELECT COUNT(DISTINCT MARKET_TOPIC) FROM MARKETING_INTEL.CURATED.SOCIAL_SENTIMENT_TRENDS → >50

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_REPORTS RESUME;
ALTER TASK IF EXISTS APP.TASK_UPDATE_TRENDS RESUME;
ALTER TASK IF EXISTS APP.TASK_ANALYZE_SOCIAL RESUME;
